// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEh4uJubuNvLcZTklCDIKrXOq5dpsu9LE',
    appId: '1:847072228396:web:7f1d58336e747c03184d89',
    messagingSenderId: '847072228396',
    projectId: 'kururin-e7956',
    authDomain: 'kururin-e7956.firebaseapp.com',
    storageBucket: 'kururin-e7956.appspot.com',
    measurementId: 'G-3N35KVQ5F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFHo6eSJ8fWO6Mh785OMTDgY-Z2biasss',
    appId: '1:847072228396:android:afe1265fa8da2f74184d89',
    messagingSenderId: '847072228396',
    projectId: 'kururin-e7956',
    storageBucket: 'kururin-e7956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv5BEPK9JavoHqNJku7tvsQJAo8yB75AI',
    appId: '1:847072228396:ios:bf9007c4479c83ac184d89',
    messagingSenderId: '847072228396',
    projectId: 'kururin-e7956',
    storageBucket: 'kururin-e7956.appspot.com',
    androidClientId: '847072228396-7odhlfkmo5o8rc4gau59bbq90pavknrt.apps.googleusercontent.com',
    iosClientId: '847072228396-m7evjqult9bs1p1igk1h6k3een4vr0v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.kururin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv5BEPK9JavoHqNJku7tvsQJAo8yB75AI',
    appId: '1:847072228396:ios:1b5f64f9f60cc810184d89',
    messagingSenderId: '847072228396',
    projectId: 'kururin-e7956',
    storageBucket: 'kururin-e7956.appspot.com',
    androidClientId: '847072228396-7odhlfkmo5o8rc4gau59bbq90pavknrt.apps.googleusercontent.com',
    iosClientId: '847072228396-g6mtk5enj7jpp9f08mjlunmgurfd5vug.apps.googleusercontent.com',
    iosBundleId: 'com.example.kururin.RunnerTests',
  );
}
